---
title: "visualize-stars"
author: "devin"
date: "January 28, 2016"
output: html_document
---


```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(PKPDmisc)
library(jsonlite)
```


```{r}
data <- read_csv("~/HR/thesis/github-stats/test_stars.csv")
data_contrib <- read_csv("~/HR/thesis/github-stats/natifier_data.csv")
```

```{r}
data <- data %>% arrange(starred_at)
data_contrib$dt <- as.POSIXct(data_contrib$time, origin = "1970-01-01")
```


```{r}
data <- data %>% mutate(count = 1, cumsum = cumsum(count)) %>% select(-count)
arranged_dt <- data_contrib %>% arrange(dt) %>% mutate(
  cumadd = cumsum(added),
  cumdel = cumsum(deleted),
  cumcommits = cumsum(commits)
) 
dt
commit_data <- arranged_dt %>% rename(date_time = dt) %>% select(cumadd, cumdel, cumcommits, date_time) %>% distinct(date_time) 
```


```{r}
data %>%
  ggplot(aes(x = starred_at, y = cumsum)) + geom_line(size = 1.5) +
  labs(x = "Star Date", y = "Total Number of Stars") + theme_bw() + base_theme() +
  geom_line(data=commit_data, aes(x = date_time, y = cumcommits), color = "blue") + scale_y_log10() +
  geom_line(data=commit_data, aes(x = date_time, y = cumadd), color = "red")
```




